server {
    listen 127.0.0.1:8080;
    listen 10.11.7.5:9090;


    server_name example.com;
    client_max_body_size 10M;

    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    location / {
        allow_methods GET POST;
        root /var/www/html;
        index index.html;
        autoindex on;
    }

    location /upload {
        allow_methods POST DELETE;
        root /var/www/uploads;
        upload_enable on;
        upload_store /var/www/uploads/files;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root /var/www/cgi-bin;
        cgi_ext .py /usr/bin/python3;
        cgi_ext .php /usr/bin/php-cgi;
    }

    location /old-path {
        return 301 https://example.com/new-path;
    }
}

server {
    listen 0.0.0.0:9090;
    server_name test.com;
    client_max_body_size 2M;

    location / {
        allow_methods GET;
        root /var/www/test;
        index default.html;
        autoindex off;
    }
}
